# Generated by Django 4.2.7 on 2024-03-05 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pretplatnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_r', models.DateField(blank=True, null=True)),
                ('spol', models.CharField(default=None, max_length=25)),
                ('adresa', models.CharField(max_length=150, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oznaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=150)),
                ('cijena', models.IntegerField()),
                ('oznake', models.ManyToManyField(blank=True, default=None, related_name='oznake', to='teretana.oznaka')),
            ],
        ),
        migrations.CreateModel(
            name='Trener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=150)),
                ('image', models.ImageField(default=None, upload_to='static/assets/img/team')),
            ],
        ),
        migrations.CreateModel(
            name='Pretplata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teretana.plan')),
                ('pretplatnik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teretana.pretplatnik')),
            ],
        ),
    ]
